flagwar-events:
    - src/com/palmergames/bukkit/towny/war/flagwar/events/*

flagwar-listeners:
    - src/com/palmergames/bukkit/towny/war/flagwar/listeners/*

github:
    - .github/*

resources:
    - resources/*