flagwar-events:
    - src/io/github/townyadvanced/flagwar/events/*

flagwar-listeners:
    - src/io/github/townyadvanced/flagwar/listeners/*

flagwar-exceptions:
    - src/io/github/townyadvanced/flagwar/exceptions/*

flagwar-objects:
    - src/io/github/townyadvanced/flagwar/objects/*

flagwar-commands:
    - src/io/github/townyadvanced/flagwar/commands/*

flagwar-configuration:
    - src/io/github/townyadvanced/flagwar/config/*
    - resources/config.yml

github:
    - .github/*

resources:
    - resources/*
    - .checkstyle/*

legal:
    - LICENSE
    - NOTICE
    - resources/LICENSE.TXT
    - resources/NOTICE.TXT
    - .github/CONTRIBUTING.MD
