name: Published Release / PreRelease

on:
    release:
        types: [released]
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up OpenJDK 11
              uses: actions/setup-java@v2
              with:
                  distribuition: 'adopt'
                  java-version: '11'
            - name: Deploy to GitHub Package Registry
              run: mvn -B deploy -P alternatives,checkstyle,javadocs
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
